sonar.projectKey=Agustin-Perezz_bus-system4
sonar.organization=general-organization

sonar.sources=src
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.spec.ts,**/*.e2e-spec.ts,**/test/**,src/main.ts,src/app.module.ts,src/instrument.ts,src/buses.module.ts,src/enterprises.module.ts,src/routes.module.ts,src/trips.module.ts,src/users.module.ts,src/infrastructure/database/database.module.ts,mikro-orm.config.ts,src/migrations/**

sonar.javascript.lcov.reportPaths=coverage/unit/lcov.info,coverage/e2e/lcov.info
sonar.qualitygate.wait=true